### ISSUE TITLE
More of a suggestion

### ISSUE THREAD

**Issue by Jagermeister56** [gabriel-milan/btrader#11]
Most successful pairs seem to have 4 trades 
at
https://eugenioclrc.github.io/binance-crypto-triangular-arbitrage

I noticed even with 0% taker fee & as little as 0.0001 trading profit there is no action taken.

**Comment by gabriel-milan** [comment]
> Most successful pairs seem to have 4 trades

Actually, no. The website you've sent me shows a list of **triangular** arbitrage trades. Please check this one for example:

- USDT → TUSD → ETH → USDT

What's happening here is:

- Buy TUSD using USDT (1st trade)
- Sell TUSD to ETH (2nd trade)
- Sell ETH to USDT (3rd trade)

That's what a **triangular** arbitrage trade is.

> I noticed even with 0% taker fee & as little as 0.0001 trading profit there is no action taken.

That probably shows the market is neither overpriced nor underpriced. If you want to see some action, please disable trading, set profits to a negative number and try again. No triangular arbitrage bot has action on the market, we just take advantage of its current prices.

**Comment by Jagermeister56** [comment]
> That probably shows the market is neither overpriced nor underpriced. If you want to see some action, please disable trading, set profits to a negative number and try again. No triangular arbitrage bot has action on the market, we just take advantage of its current prices.

That website seems to think there are possible combinations, even if it's only 0.02% of profit after fees.

**Comment by gabriel-milan** [comment]
> That website seems to think there are possible combinations, even if it's only 0.02% of profit after fees.

It seems like it fetches data directly from your browser. If so, any latency between you and `api.binance.com` will change the results. That's why I recommend running this kind of stuff on a VM or something with very low latency to the API (<5ms). Besides that, profit calculations implementation may differ from one project to another (this doesn't mean that one is better than the other).

Anyway, if you find any inconsistency on my profit calculation, I'll be happy to take a look at it on my free time, I can't be 100% sure it's fail-proof. Otherwise, this is not an issue, nor a suggestion, and I'll close it soon.

**Comment by Jagermeister56** [comment]
Sounds good, i'll close it up
