### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by rhjelove** [gabriel-milan/btrader#13]
Hi, I just followed the instructions and ran into this problem. Could you please help?
![Untitled](https://user-images.githubusercontent.com/110790087/183311649-5b60e4ce-70e0-4b32-825d-5dd5165bda34.png)

**Comment by marmibv** [comment]
in Cargo.toml modify like this
[dependencies]
binance = "*"
serde = { version = "1.0" }
serde_json = { version = "1.0" }
rayon = "*"
indicatif = "*"
console = "*"
telegram-bot = "*"
futures="*"
tokio = { version = "*", features = ["macros", "io-util"] }

**Comment by marmibv** [comment]
in "" put *.
like this binance = "*"

**Comment by rhjelove** [comment]
Hi,

Thanks a lot!
But could you please explain it, because I'm a little confused and don't
understand correctly where I should replace this:

in "" put
*. like this binance = "*"


------

My current Cargo.toml

[package]
name = "btrader"
version = "0.2.0"
authors = ["Gabriel Gazola Milan ***@***.***>"]
edition = "2018"
description = "Arbitrage trading bot for Binance"
homepage = "https://github.com/gabriel-milan/btrader"
repository = "https://github.com/gabriel-milan/btrader"
license="GPL-3.0"
keywords=["bot", "algotrading", "cryptocurrencies", "binance", "arbitrage"]

# See more keys and their definitions at
https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance = ""
serde = { version = "1.0" }
serde_json = { version = "1.0" }
rayon = ""
indicatif = ""
console = ""
telegram-bot = ""
futures=""
tokio = { version = "*", features = ["macros", "io-util"] }

[lib]
name = "btrader"
path = "src/lib.rs"

**Comment by marmibv** [comment]
YesSent from my phone-------- Original message --------From: rhjelove ***@***.***>Date: Tue, Aug 9, 2022, 3:20 PMTo: gabriel-milan/btrader ***@***.***>Cc: Mihaiu Marius ***@***.***>, Comment ***@***.***>Subject: Re: [gabriel-milan/btrader] Launch problem (Issue #13)

Hi,



Thanks a lot!

But could you please explain it, because I'm a little confused and don't

understand correctly where I should replace this:



in "" put

*. like this binance = "*"





------



My current Cargo.toml



[package]

name = "btrader"

version = "0.2.0"

authors = ["Gabriel Gazola Milan ***@***.***>"]

edition = "2018"

description = "Arbitrage trading bot for Binance"

homepage = "https://github.com/gabriel-milan/btrader"

repository = "https://github.com/gabriel-milan/btrader"

license="GPL-3.0"

keywords=["bot", "algotrading", "cryptocurrencies", "binance", "arbitrage"]



# See more keys and their definitions at

https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]

binance = ""

serde = { version = "1.0" }

serde_json = { version = "1.0" }

rayon = ""

indicatif = ""

console = ""

telegram-bot = ""

futures=""

tokio = { version = "*", features = ["macros", "io-util"] }



[lib]

name = "btrader"

path = "src/lib.rs"

**Comment by marmibv** [comment]
yes

**Comment by rhjelove** [comment]
Thank you for your response!
I have this error now:

C:\Users\Administrator\Desktop\btrader\btrader>cargo install --path .
error: failed to parse manifest at
`C:\Users\Administrator\Desktop\btrader\btrader\Cargo.toml`

Caused by:
  failed to parse the version requirement `` for dependency `console`

Caused by:
  unexpected end of input while parsing major version number

C:\Users\Administrator\Desktop\btrader\btrader>

**Comment by marmibv** [comment]
try this repo https://github.com/marmibv/btrader-arbitrage

**Comment by rhjelove** [comment]
I have added a new repo but still getting the error:

C:\Users\Administrator\Desktop\btrader\btrader>btrader
C:\Users\Administrator\Desktop\btrader\btrader\config\sample_config.json
[1/7] Connecting to Binance... Successfully connected!
thread 'main' panicked at 'Error on getting exchange info: unknown variant
`TRAILING_DELTA`, expected one of `PRICE_FILTER`, `PERCENT_PRICE`,
`LOT_SIZE`, `MIN_NOTIONAL`, `ICEBERG_PARTS`, `MAX_NUM_ORDERS`,
`MAX_NUM_ALGO_ORDERS`, `MAX_NUM_ICEBERG_ORDERS`, `MAX_POSITION`,
`MARKET_LOT_SIZE` at line 1 column 1453', src\trader.rs:41:17
note: run with `RUST_BACKTRACE=1` environment variable to display a
backtrace
[2/7] Getting trading pairs...
C:\Users\Administrator\Desktop\btrader\btrader>

**Comment by marmibv** [comment]
for me work fine

**Comment by marmibv** [comment]
you modify cargo.toml in the second repo you have to leave it as it is and it should work for you if it doesn't uninstall rust and install it again because some of the files also go to appdata

**Comment by marmibv** [comment]
in the appdata folder, delete the rust or cargo directory and install again the app

**Comment by marmibv** [comment]
sorry for the bad english

**Comment by marmibv** [comment]
if not try this is the same written in javascript https://github.com/marmibv/binance-triangle-arbitrage
